### ISSUE TITLE
URL generated for gitlab.com and Personal Access Token

### ISSUE THREAD

**Issue by clerousset** [InseeFrLab/legacy-onyxia-entrypoint#41]
Launching a Rstudio instance with a gitlab.com predefinied Git repository and a Personal Access Token generates a wrong URL. 
`git remote get-url origin` is https://<PAT>@gitlab.com/<project>.git instead of requested https://oauth2:<PAT>@gitlab.com/<project>

**Comment by garronej** [comment]
Merci pour l'issue 

@fcomte Peut être tu te sent de prendre ça?

**Comment by fcomte** [comment]
done https://github.com/InseeFrLab/onyxia/commit/f26168f82afc91cb80cdad2b6693d2d8137d744c
