### ISSUE TITLE
[feature request] Choosing git branch in the GIT tab of a Rstudio service

### ISSUE THREAD

**Issue by clerousset** [InseeFrLab/legacy-onyxia-entrypoint#43]
the Git tab of a service could ask for an optional branch so that the user is directly in that branch at the beginning of a service.

**Comment by garronej** [comment]
Hey @clerousset,  

It's done:   

![image](https://user-images.githubusercontent.com/6702424/177005081-037c05b1-4320-46e7-90c0-60f3ef6c2028.png)
